theme: minima
title: My resume
author: Victor Mwai
description: I am a dedicated learner in Cyber Security. I am currently taking various short courses in the field next to my Bsc studies and my curiosity to understand networks and how the internet works pushes me to add more knowledge in this fields too. Furthermore,I am focused,a team player and self-driven learner.I play CTFs with various teams including nighthawks.I am open to further learning to help in my journey to becoming a specialized expert in the field.
